---
- hosts: my_servers
  become: true
  tasks:
    - name: Create a folder in the /home/azureuser directory
      ansible.builtin.file:
        path: /home/azureuser/semaphorefolder
        state: directory
        mode: '0755' 
      become_user: azureuser 
